### ISSUE TITLE
AMF keeps crashing when deployed

### ISSUE THREAD

**Issue by marcohol1** [edgecomllc/open5gs-compose#2]
Hello,

I have been using your Open5GS image and it has been working normally. However, I deployed it in an AWS Ubuntu instance today and all the network functions are deployed properly except for the AMF. This is the error in the logs. Do you have any insights as to how to solve this?

![image](https://github.com/edgecomllc/open5gs-compose/assets/144364350/8f40b4bc-8313-4ec8-be38-218816a2bcad)

Thank you very much and have a nice day!

Best regards,
Marco

**Comment by pirog-spb** [comment]
Hi Marco,

Seems like not the image issue. According to open5gs source code such assertion is caused by malloc error.

```
ogs_pool_init(&amf_gnb_pool, ogs_global_conf()->max.peer*2);
```

```
#define ogs_pool_init(pool, _size) do { \
    ...
    (pool)->array = malloc(sizeof(*(pool)->array) * _size); \
    ogs_assert((pool)->array); \
    ...
``` 

So looks like you configured too many gnb peers or you have lack of RAM in AWS

-- BR, Alex

**Comment by marcohol1** [comment]
Hi Alex,

Thank you so much for your insight! I changed the global variable in the config of AMF to lower the UEs and peers to 32 and 2 respectively. I now receive this new error. Do you think it's just now the lack of RAM that is the problem since I am only using t3.micro that only has 1GiB memory?

![image](https://github.com/edgecomllc/open5gs-compose/assets/144364350/25e95b31-49e2-4420-a5b1-d093a7a11709)


Best regards,
Marco

**Comment by marcohol1** [comment]
Hi Alex,

I deployed it using another instance type (t3.small) and it worked as expected! I think it is indeed the lack of memory.

Thank you very much for your help and have a nice day!

Best regards,
Marco
